### ISSUE TITLE
Screen1 don't show on app

### ISSUE THREAD

**Issue by becschatz** [seinecle/codapps#120]
After creating screen1 it says the following
BUILD SUCCESSFUL (total time: 2 seconds)
however no screen pops up to check if I built screen 1 correctly 

thanks

**Comment by seinecle** [comment]
To preview your app, follow these steps:

https://seinecle.github.io/codapps/generated-html/creating-your-first-project-and-previewing-your-app.html#_2_done_preview_your_app

**Comment by becschatz** [comment]
Seinecle, when I press the green arrow it does not give me a preview of my app, nothing pops up

**Comment by seinecle** [comment]
Can you copy paste here all the lines in red that appear at the bottom, showing the errors?

**Comment by becschatz** [comment]
java.lang.NullPointerException
	at com.codename1.ui.Font.<init>(Font.java:194)
	at com.codename1.ui.Font.createSystemFont(Font.java:418)
	at com.codename1.ui.plaf.UIManager.resetThemeProps(UIManager.java:401)
	at com.codename1.ui.plaf.UIManager.<init>(UIManager.java:106)
	at com.codename1.ui.plaf.UIManager.getInstance(UIManager.java:124)
	at com.codename1.ui.Component.getUIManager(Component.java:850)
	at com.codename1.ui.Component.<init>(Component.java:639)
	at com.codename1.ui.Label.<init>(Label.java:98)
	at schatz.redsnutrition.MyApplication.<init>(MyApplication.java:60)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at com.codename1.impl.javase.Executor$1.run(Executor.java:105)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Java Result: 1

**Comment by seinecle** [comment]
Ok thanks. Can you also post the entire code of MyApplication.java please?

**Comment by becschatz** [comment]
Hi again, apologies but I restarted my project, and I've created Screen1 then press the green button and a new window pops up, but its just black 


![image](https://user-images.githubusercontent.com/40331942/41512151-e77031d4-72c7-11e8-84c5-5ee23b76aee6.png)

this is MyApplicationo,java code
package schatz.redsnutrition;


import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.NetworkEvent;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }
    
    public void start() {
        Screen1 box;
        box = new Screen1();
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

}

**Comment by seinecle** [comment]
A line is missing.  Do:

public void start() {
Screen1 box;
box = new Screen1();
**box.show();**
}

The line tells your app to show the screen, without it the screen is created but never shown, the app remains black.

**Comment by becschatz** [comment]
Thankyou so much ! much appreciated :)
